"""
Desktop app entry point — opens a pywebview window on the homepage instead of
running scripts by hand.

Every page shown here (the homepage included) is generated by its own
view_*.py script, unchanged and independently runnable. Nav clicks call back
into Api.navigate() below (see modules/layout.py's navigateTo()): with
auto-refresh ON (default) the target script re-runs before the page is shown;
OFF, the last generated file is shown as-is, only running the script if it
doesn't exist yet. If a script fails, the page shows a red error banner
(Api.get_error(), polled by the page itself on load).
"""

import os
import subprocess
import sys
import threading
import time

import webview

import do_zip_backup
from modules.layout import PAGES

RUNTIME_DIR = os.path.dirname(os.path.abspath(__file__))
VIEW_DIR = os.path.abspath(os.path.join(RUNTIME_DIR, "..", "exports", "view"))
HOMEPAGE_PATH = os.path.join(VIEW_DIR, "homepage.html")

SCRIPT_BY_PAGE = {file: script for file, _label, script, _is_edit in PAGES}


def _run_script(script_name):
    """Run a view_*.py the same way a user would from a terminal, just
    quieted down (no "press Enter to close", no popping a separate browser
    window) since the webview window is about to display the result itself.
    Returns the last non-empty line of stderr on failure, None on success."""
    print(f"→ {script_name}")
    env = os.environ.copy()
    env["COMPTA_WEBVIEW"] = "1"
    result = subprocess.run(
        [sys.executable, script_name], cwd=RUNTIME_DIR, env=env,
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(f"✓ {script_name} — succès")
        return None
    lines = [l for l in result.stderr.splitlines() if l.strip()]
    error = lines[-1] if lines else f"{script_name} a échoué (code {result.returncode})"
    print(f"✗ {script_name} — {error}")
    return error


class Api:
    """Exposed to the generated pages as `pywebview.api` (see modules/layout.py)."""

    def __init__(self):
        self.auto_refresh = True
        self.errors = {}  # filename -> last error message, cleared on next success

    def get_auto_refresh(self):
        return self.auto_refresh

    def set_auto_refresh(self, value):
        self.auto_refresh = bool(value)

    def get_error(self, filename):
        return self.errors.get(filename)

    def run(self, filename):
        """(Re)generate one page's file, recording success/failure."""
        script = SCRIPT_BY_PAGE.get(filename)
        if not script:
            return
        error = _run_script(script)
        if error:
            self.errors[filename] = error
        else:
            self.errors.pop(filename, None)

    def navigate(self, filename):
        """Called by the page's JS before it navigates itself to `filename`
        (see navigateTo() in modules/layout.py). Only (re)generates the file
        here — the actual navigation happens in JS once this returns, so the
        page doing the navigating is never the same page pywebview is still
        trying to deliver this call's result to."""
        target_path = os.path.join(VIEW_DIR, filename)
        if filename in SCRIPT_BY_PAGE and (self.auto_refresh or not os.path.isfile(target_path)):
            self.run(filename)

    def backup_database(self):
        """Zip database/ to exports/backups/ and open that folder, for the
        navbar's zip button (see modules/layout.py)."""
        print("→ backup database (zip)")
        try:
            zip_path = do_zip_backup.make_backup(open_folder=True)
        except Exception as e:
            print(f"✗ backup — {e}")
            return {"ok": False, "error": str(e)}
        if zip_path is None:
            print("✗ backup — dossier database introuvable")
            return {"ok": False, "error": "dossier database introuvable"}
        print(f"✓ backup — {zip_path}")
        return {"ok": True, "path": zip_path}

    def fetch_calendar_preview(self, ym):
        """On-demand Google Calendar fetch for the Calendrier page's preview
        button — never runs on page open, only when the user clicks it, since
        the network round-trip can take a while."""
        print(f"→ calendar preview ({ym})")
        try:
            from tools.calendar_export import (
                load_ical_url, fetch_ics, parse_events, build_matchers,
                resolve_event, read_existing_entries, month_range, WEEKDAY_FR,
            )
            from packages.database.database import Database

            range_start, range_end = month_range(ym)
            ics_bytes = fetch_ics(load_ical_url())
            events = parse_events(ics_bytes, range_start, range_end)
            uid_map, name_map = build_matchers(Database.init_billing())
            existing_entries = read_existing_entries(ym)
        except Exception as e:
            print(f"✗ calendar preview — {e}")
            return {"ok": False, "error": str(e)}

        rows = []
        for event_date, raw_title in events:
            uid, fraction, status = resolve_event(raw_title, uid_map, name_map)
            local, existing_fraction = None, None
            if uid:
                existing_fraction = existing_entries.get((event_date.day, uid))
                if existing_fraction is None:
                    local = "new"
                elif abs(existing_fraction - fraction) < 1e-9:
                    local = "match"
                else:
                    local = "conflict"
            rows.append({
                "date": str(event_date),
                "weekday": WEEKDAY_FR[event_date.weekday()],
                "title": raw_title,
                "uid": uid or "",
                "fraction": fraction,
                "status": status,
                "local": local,
                "existing_fraction": existing_fraction,
            })
        print(f"✓ calendar preview — {len(rows)} event(s)")
        return {"ok": True, "rows": rows}

    def import_calendar_entry(self, ym, date_str, uid, fraction, replace=False):
        """Write one resolved calendar row into database/tasks/{ym}.task —
        called by the Calendrier page's per-row and "Importer tout" buttons.
        A project already declared that day with the same fraction is a
        no-op (skipped); a different fraction is left untouched and reported
        as a conflict unless replace=True (the UI confirms with the user
        first). Several projects can share the same day without conflict."""
        if not uid:
            return {"ok": False, "error": "aucun projet résolu"}
        print(f"→ import calendar entry {date_str} → {uid} ({fraction}){' [replace]' if replace else ''}")
        try:
            from tools.calendar_export import write_task_entry
            day = int(date_str.split("-")[-1])
            result = write_task_entry(ym, day, uid, float(fraction), replace=bool(replace))
        except Exception as e:
            print(f"✗ import — {e}")
            return {"ok": False, "error": str(e)}
        if result.get("conflict"):
            print(f"✗ import — conflit ({result.get('existing_fraction')} existant)")
        else:
            print(f"✓ import — {'déjà présent' if result.get('skipped') else 'ajouté'}")
        return result

    def update_bill_range(self, project_uid, bill_uid, new_start, new_end):
        """Rewrite one existing bill's start/end period -- called by the
        Éditer les factures page's per-row "Enregistrer" button."""
        print(f"→ update bill {project_uid}/{bill_uid} → {new_start}..{new_end}")
        try:
            from tools.bill_editor import update_bill_range
            result = update_bill_range(project_uid, bill_uid, new_start, new_end)
        except Exception as e:
            print(f"✗ update bill — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ update bill" if result.get("ok") else f"✗ update bill — {result.get('error')}")
        return result

    def add_bill(self, project_uid, bill_uid, start, end):
        """Append a new bill for a project -- called by the Éditer les
        factures page's "Ajouter une facture" form."""
        print(f"→ add bill {project_uid}/{bill_uid} → {start}..{end}")
        try:
            from tools.bill_editor import add_bill
            result = add_bill(project_uid, bill_uid, start, end)
        except Exception as e:
            print(f"✗ add bill — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ add bill" if result.get("ok") else f"✗ add bill — {result.get('error')}")
        return result

    def delete_bill(self, project_uid, bill_uid):
        """Delete one bill -- called by the Éditer les factures page's
        per-row "Supprimer" button. Refuses if a wire is already linked to
        it (see tools/bill_editor.py: delete_bill())."""
        print(f"→ delete bill {project_uid}/{bill_uid}")
        try:
            from tools.bill_editor import delete_bill
            result = delete_bill(project_uid, bill_uid)
        except Exception as e:
            print(f"✗ delete bill — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ delete bill" if result.get("ok") else f"✗ delete bill — {result.get('error')}")
        return result

    def add_wire(self, client_uid, date, amount, bill_fuid=""):
        """Append a new received wire transfer -- called by the Virements
        page's "Ajouter un virement" form."""
        print(f"→ add wire {client_uid} {date} {amount}{' → ' + bill_fuid if bill_fuid else ''}")
        try:
            from tools.wire_editor import add_wire
            result = add_wire(client_uid, date, amount, bill_fuid)
        except Exception as e:
            print(f"✗ add wire — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ add wire" if result.get("ok") else f"✗ add wire — {result.get('error')}")
        return result

    def associate_wire(self, filename, line_no, bill_fuid):
        """Set or clear a wire's bill association -- called by the Virements
        page's per-row "Associer" control."""
        print(f"→ associate wire {filename}:{line_no} → {bill_fuid or '(aucune)'}")
        try:
            from tools.wire_editor import associate_wire
            result = associate_wire(filename, line_no, bill_fuid)
        except Exception as e:
            print(f"✗ associate wire — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ associate wire" if result.get("ok") else f"✗ associate wire — {result.get('error')}")
        return result

    def update_client(self, uid, name, address, creditor="", country="", tva="", color=""):
        """Update one client's info -- called by the Clients page's per-row
        "Enregistrer" button."""
        print(f"→ update client {uid}")
        try:
            from tools.client_editor import update_client
            result = update_client(uid, name, address, creditor, country, tva, color)
        except Exception as e:
            print(f"✗ update client — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ update client" if result.get("ok") else f"✗ update client — {result.get('error')}")
        return result

    def add_client(self, uid, name, address, creditor="", country="", tva="", color=""):
        """Create a new client -- called by the Clients page's "Ajouter un
        client" form."""
        print(f"→ add client {uid}")
        try:
            from tools.client_editor import add_client
            result = add_client(uid, name, address, creditor, country, tva, color)
        except Exception as e:
            print(f"✗ add client — {e}")
            return {"ok": False, "error": str(e)}
        print("✓ add client" if result.get("ok") else f"✗ add client — {result.get('error')}")
        return result

    def generate_bill_pdf(self, project_uid, bill_uid):
        """Generate (or regenerate) one bill's PDF on demand and open it --
        called by the Éditer les factures page's per-row "PDF" button."""
        print(f"→ generate pdf {project_uid}/{bill_uid}")
        try:
            from tools.bill_pdf import generate_bill_pdf
            result = generate_bill_pdf(project_uid, bill_uid)
        except Exception as e:
            print(f"✗ generate pdf — {e}")
            return {"ok": False, "error": str(e)}
        if result.get("ok"):
            print(f"✓ generate pdf — {result.get('path')}")
            if hasattr(os, "startfile"):
                os.startfile(result["path"])
        else:
            print(f"✗ generate pdf — {result.get('error')}")
        return result

    def restart(self):
        """Close this window and relaunch the app in a new process. Runs the
        actual close on a delay/background thread, same reasoning as
        navigate(): closing the window from inside the js_api call that
        triggered it would race pywebview trying to deliver this call's
        result back to a window that's already gone."""
        threading.Thread(target=self._do_restart, daemon=True).start()

    def _do_restart(self):
        subprocess.Popen([sys.executable, "app_gui.py"], cwd=RUNTIME_DIR)
        time.sleep(0.3)
        for window in webview.windows:
            window.destroy()


if __name__ == "__main__":
    api = Api()
    api.run("homepage.html")

    webview.create_window(
        "compta_python", HOMEPAGE_PATH, width=1200, height=800, js_api=api,
    )

    webview.start()
