"""
Desktop app entry point — opens a pywebview window on the homepage instead of
running scripts by hand.

Every page shown here (the homepage included) is generated by its own
view_*.py script, unchanged and independently runnable. Nav clicks call back
into Api.navigate() below (see modules/layout.py's navigateTo()): with
auto-refresh ON (default) the target script re-runs before the page is shown;
OFF, the last generated file is shown as-is, only running the script if it
doesn't exist yet. If a script fails, the page shows a red error banner
(Api.get_error(), polled by the page itself on load).
"""

import os
import subprocess
import sys
import threading
import time

import webview

import do_zip_backup
from modules.layout import PAGES

RUNTIME_DIR = os.path.dirname(os.path.abspath(__file__))
VIEW_DIR = os.path.abspath(os.path.join(RUNTIME_DIR, "..", "exports", "view"))
HOMEPAGE_PATH = os.path.join(VIEW_DIR, "homepage.html")

SCRIPT_BY_PAGE = {file: script for file, _label, script in PAGES}


def _run_script(script_name):
    """Run a view_*.py the same way a user would from a terminal, just
    quieted down (no "press Enter to close", no popping a separate browser
    window) since the webview window is about to display the result itself.
    Returns the last non-empty line of stderr on failure, None on success."""
    print(f"→ {script_name}")
    env = os.environ.copy()
    env["COMPTA_WEBVIEW"] = "1"
    result = subprocess.run(
        [sys.executable, script_name], cwd=RUNTIME_DIR, env=env,
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(f"✓ {script_name} — succès")
        return None
    lines = [l for l in result.stderr.splitlines() if l.strip()]
    error = lines[-1] if lines else f"{script_name} a échoué (code {result.returncode})"
    print(f"✗ {script_name} — {error}")
    return error


class Api:
    """Exposed to the generated pages as `pywebview.api` (see modules/layout.py)."""

    def __init__(self):
        self.auto_refresh = True
        self.errors = {}  # filename -> last error message, cleared on next success

    def get_auto_refresh(self):
        return self.auto_refresh

    def set_auto_refresh(self, value):
        self.auto_refresh = bool(value)

    def get_error(self, filename):
        return self.errors.get(filename)

    def run(self, filename):
        """(Re)generate one page's file, recording success/failure."""
        script = SCRIPT_BY_PAGE.get(filename)
        if not script:
            return
        error = _run_script(script)
        if error:
            self.errors[filename] = error
        else:
            self.errors.pop(filename, None)

    def navigate(self, filename):
        """Called by the page's JS before it navigates itself to `filename`
        (see navigateTo() in modules/layout.py). Only (re)generates the file
        here — the actual navigation happens in JS once this returns, so the
        page doing the navigating is never the same page pywebview is still
        trying to deliver this call's result to."""
        target_path = os.path.join(VIEW_DIR, filename)
        if filename in SCRIPT_BY_PAGE and (self.auto_refresh or not os.path.isfile(target_path)):
            self.run(filename)

    def backup_database(self):
        """Zip database/ to exports/backups/ and open that folder, for the
        navbar's zip button (see modules/layout.py)."""
        print("→ backup database (zip)")
        try:
            zip_path = do_zip_backup.make_backup(open_folder=True)
        except Exception as e:
            print(f"✗ backup — {e}")
            return {"ok": False, "error": str(e)}
        if zip_path is None:
            print("✗ backup — dossier database introuvable")
            return {"ok": False, "error": "dossier database introuvable"}
        print(f"✓ backup — {zip_path}")
        return {"ok": True, "path": zip_path}

    def fetch_calendar_preview(self, ym):
        """On-demand Google Calendar fetch for the Calendrier page's preview
        button — never runs on page open, only when the user clicks it, since
        the network round-trip can take a while."""
        print(f"→ calendar preview ({ym})")
        try:
            from tools.calendar_export import (
                load_ical_url, fetch_ics, parse_events, build_matchers,
                resolve_event, month_range, WEEKDAY_FR,
            )
            from packages.database.database import Database

            range_start, range_end = month_range(ym)
            ics_bytes = fetch_ics(load_ical_url())
            events = parse_events(ics_bytes, range_start, range_end)
            uid_map, name_map = build_matchers(Database.init_billing())
        except Exception as e:
            print(f"✗ calendar preview — {e}")
            return {"ok": False, "error": str(e)}

        rows = []
        for event_date, raw_title in events:
            uid, fraction, status = resolve_event(raw_title, uid_map, name_map)
            rows.append({
                "date": str(event_date),
                "weekday": WEEKDAY_FR[event_date.weekday()],
                "title": raw_title,
                "uid": uid or "",
                "fraction": fraction,
                "status": status,
            })
        print(f"✓ calendar preview — {len(rows)} event(s)")
        return {"ok": True, "rows": rows}

    def restart(self):
        """Close this window and relaunch the app in a new process. Runs the
        actual close on a delay/background thread, same reasoning as
        navigate(): closing the window from inside the js_api call that
        triggered it would race pywebview trying to deliver this call's
        result back to a window that's already gone."""
        threading.Thread(target=self._do_restart, daemon=True).start()

    def _do_restart(self):
        subprocess.Popen([sys.executable, "app_gui.py"], cwd=RUNTIME_DIR)
        time.sleep(0.3)
        for window in webview.windows:
            window.destroy()


if __name__ == "__main__":
    api = Api()
    api.run("homepage.html")

    webview.create_window(
        "compta_python", HOMEPAGE_PATH, width=1200, height=800, js_api=api,
    )

    webview.start()
